# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-25 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merk', models.CharField(max_length=200)),
                ('tipe', models.CharField(max_length=200)),
                ('spesifikasi', models.TextField()),
                ('harga', models.CharField(max_length=50, verbose_name='Harga Barang')),
                ('publish', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, editable=False)),
            ],
        ),
    ]
