# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-31 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('tipe', models.CharField(max_length=20)),
                ('start', models.CharField(max_length=5)),
                ('end', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'course',
            },
        ),
    ]
