# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-25 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handphone', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='handphone',
            old_name='publis',
            new_name='publish',
        ),
    ]
